# ===================================================================
# CONFIGURAÇÕES DE CONEXÃO COM O POSTGRESQL
# ===================================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/portfolio_db
spring.datasource.username=postgres
spring.datasource.password=keyblade
spring.datasource.driver-class-name=org.postgresql.Driver

# ===================================================================
# CONFIGURAÇÕES DO HIBERNATE / JPA
# ===================================================================
# update: O Hibernate atualiza a estrutura do banco dinamicamente baseado nas entidades Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===================================================================
# CONFIGURAÇÕES DO SWAGGER UI / OPENAPI
# ===================================================================
# Ativa explicitamente o endpoint e define o caminho padrão do HTML
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

